apiVersion: apps/v1
kind: Deployment
metadata:
  name: gobackend-depl
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gobackend
  template:
    metadata:
      labels:
        app: gobackend
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
