apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: gobackend
  ports:
    - name: gobackend
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080